apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-task-two-docker-build-push
spec:
  params:
    - name: IMAGE_REPO
      description: The image registry
    - name: IMAGE_TAG
      description: tag of the docker image
  resources:
    inputs:
      - name: repo
        type: git
  steps:

  ## ----------- Task 1 ----------- 
    - name: ubuntu-test
      image: ubuntu
      workingDir: /workspace/repo
      script: |
         echo $(cut -d'=' -f2 version) > /workspace/repo/version

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:debug-v0.19.0
      workingDir: /workspace/repo
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      script: |
         #!/busybox/sh
         echo "Task 4 - Start Golang Build"
         /kaniko/executor --dockerfile Dockerfile  --context `pwd` --destination=$(params.IMAGE_REPO):$(cut -d'=' -f2 version)
         echo "Task 4 - Start Golang Build"
--- 


#apiVersion: tekton.dev/v1beta1
#kind: TaskRun
#metadata:
#  name: taskrun-build-and-push
#spec:
#  serviceAccountName: golang-service-account
#  taskRef:
#    name: golang-task-two-docker-build-push
#  resources:
#    inputs:
#      - name: repo
#        resourceRef:
#          name: golang-pipeline-resource