apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-task-two-docker-build-push
spec:
  # params:
  #   - name: IMAGE_REPO
  #     description: The image registry
  resources:
    inputs:
      - name: repo
        type: git
  steps:

  ## ----------- Task 1 ----------- 
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:debug-v0.19.0
      workingDir: /workspace/repo
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      script: |
         #!/busybox/sh
         echo "Start Docker Build and Push"
         registry=`awk 'NR == 6' GoBackend/values.yaml | cut -d':' -f2 | cut -d' ' -f2`
         image=`awk 'NR == 7' GoBackend/values.yaml | cut -d':' -f2 | cut -d' ' -f2`
         tag=`awk 'NR == 24' GoBackend/Chart.yaml | cut -d':' -f2 | cut -d' ' -f2`
         imageRepo=$registry/$image


         /kaniko/executor --dockerfile Dockerfile  --context `pwd` --destination=$imageRepo:$tag
         echo "Image Built: " $imageRepo:$tag
         echo "End Docker Build and Push"
--- 


#apiVersion: tekton.dev/v1beta1
#kind: TaskRun
#metadata:
#  name: taskrun-build-and-push
#spec:
#  serviceAccountName: golang-service-account
#  taskRef:
#    name: golang-task-two-docker-build-push
#  resources:
#    inputs:
#      - name: repo
#        resourceRef:
#          name: golang-pipeline-resource