apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /hooks
            pathType: Exact
            backend:
              serviceName: el-github-pr
              servicePort: 8080