apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-task-two-docker-build-push
spec:
  params:
    - name: IMAGE_REPO
      description: The image registry
    - name: IMAGE_TAG
      description: tag of the docker image
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.3.0
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
        - --dockerfile=Dockerfile
        - --context=/workspace/repo
        - --destination=$(params.IMAGE_REPO):$(params.IMAGE_TAG)

--- 


#apiVersion: tekton.dev/v1beta1
#kind: TaskRun
#metadata:
#  name: taskrun-build-and-push
#spec:
#  serviceAccountName: golang-service-account
#  taskRef:
#    name: golang-task-two-docker-build-push
#  resources:
#    inputs:
#      - name: repo
#        resourceRef:
#          name: golang-pipeline-resource