apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: golang-pipeline-resource
spec:
  type: git
  params:
    - name: url
      value: git@github.com:arrelpoblete04/GolangBackend.git #URL of repository.
    - name: revision
      value: master