apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-pr-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrepositoryurl
      value: $(body.repository.git_url)
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitbranch
      value: $(body.ref)