apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-task-two-docker-build-push
spec:
  params:
    - name: IMAGE_TAG
    - name: IMAGE_REPO
    - name: ARGO_APP
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.3.0
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
        - --dockerfile=Dockerfile
        - --context=/workspace/repo
        - --destination=$(params.IMAGE_REPO):$(params.IMAGE_TAG)

#    - name: deploy-argocd
#      image: argoproj/argocd:v1.7.7
#      env:
#      - name: ARGOCD_SERVER
#        value: argocd-server.argocd
#      script: |
#        #!/usr/bin/env sh
#        echo "Start Deploying Argo!"
#       set -e      
#        argocd app sync $(params.ARGO_APP) --insecure
#        argocd app wait $(params.ARGO_APP) --sync --health --operation --insecure

--- 


#apiVersion: tekton.dev/v1beta1
#kind: TaskRun
#metadata:
#  name: taskrun-build-and-push
#spec:
#  serviceAccountName: golang-service-account
#  taskRef:
#    name: golang-task-two-docker-build-push
#  resources:
#    inputs:
#      - name: repo
#        resourceRef:
#          name: golang-pipeline-resource