apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: golang-build-pipeline
spec:
  serviceAccountName: golang-service-account
  pipelineRef:
    name: golang-pipeline
  resources:
  - name: repo
    resourceRef:
      name: golang-pipeline-resource