apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-dotnet-pr-binding
spec:
  params:
    - name: gitrepositoryurl
      value: $(body.repository.ssh_url)
    - name: gitrevision
      value: $(body.head_commit.id)