apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dotnet-pipeline
spec:
  resources:
    - name: repo
      type: git

  tasks:
     # Build docker image and push to registry
    - name: stage-one-build-and-push
      params: ## These are the params needed on the Task two
          - name: IMAGE_REPO
            value: 'registry.ns0.civo.com/dotnet/images'
      taskRef:
        name: dotnet-task-one-docker-build-push
      # runAfter: ## With this spec, this task will only run after the stage-one-go-build
      #   - stage-one-go-build
      resources:
        inputs:
          - name: repo      # name of the Task input (see Task definition)
            resource: repo  # name of the Pipeline resource
