apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-development
  #namespace: development
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Atlas
    repoURL: https://github.com/arrelpoblete04/Atlas.git
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: null
    syncOptions:
      - Validate=true
      - CreateNamespace=true