apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: default
spec:
  project: default
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
         prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
         selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
         allowEmpty: true
  source:
    repoURL: git@github.com:arrelpoblete04/Atlas.git
    targetRevision: master
    path: Atlas
    helm:
      valueFiles:
        - 'values.yaml'
  destination:
    server: https://kubenetes.default.svc
    namespace: default