apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: default
spec:
  project: default
  source:
    repoURL: git@github.com:arrelpoblete04/Atlas.git
    targetRevision: master
    path: Atlas
    helm:
      valueFiles:
        - 'values.yaml'
  destination:
    server: https://212.2.241.234:6443
    namespace: default