apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/docker-0: registry.ns0.civo.com
type: kubernetes.io/basic-auth
data:
    username: YXJyZWxwb2JsZXRl 
    password: UGFzc3dvcmQxMjM0NQ==