apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /argo
            pathType: Exact
            backend:
              serviceName: argocd-server
              servicePort: 443