apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgd
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: master
        url: https://kubernetes.default.svc
        repo: git@github.com:arrelpoblete04/GolangBackend.git
      - cluster: stage
        url: https://kubernetes.default.svc
        repo: git@github.com:arrelpoblete04/GolangBackend.git
  template:
    metadata:
      name: '{{cluster}}-bgd'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: '{{repo}}'
        targetRevision: '{{cluster}}'
        path: GoBackend
        helm:
      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
          valueFiles:
          - 'values-{{cluster}}.yaml'
      destination:
        server: '{{url}}'
        namespace: '{{{{cluster}}}}'