apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  name: argocd-env-secret
type: Opaque
stringData:
  username: admin
  password: G9XEMGd7moTCuaXL

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  # Replace ARGOCD_SERVER with your ArgoCD server name (see https://medium.com/dzerolabs/installing-ambassador-argocd-and-tekton-on-kubernetes-540aacc983b9)
  ARGOCD_SERVER: 10.43.193.88:443
  ARGOCD_APPLICATION_NAME: tekton-pipeline-app
  ARGOCD_APPLICATION_REVISION: HEAD