apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-tekton-pipeline
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: GoBackend 
    repoURL: 'https://github.com/arrelpoblete04/GolangBackend'
    targetRevision: master

  syncPolicy:
    automated: {}