apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: backendgolang-canary
      stableService: backendgolang
      trafficRouting:
        nginx:
          stableIngress: ingress-stable
      steps:
      - setWeight: 5
      - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backendgolang
  template:
    metadata:
      labels:
        app: backendgolang
    spec:
      containers:
      - name: rollouts-demo
        image: registry.ns0.civo.com/images/golangbackend:1.1.8-stage
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m