apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/docker-0: registry.ns0.civo.com
type: kubernetes.io/basic-auth
data:
    username: YXJyZWxwb2JsZXRl  ## https://www.base64decode.org/ -> encode
    password: UGFzc3dvcmQxMjM0NQ==  ## https://www.base64decode.org/ -> encode

--- 

apiVersion: v1
kind: Secret
metadata:
  name: git-user
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data: #for ssh private kwy, copy the ~/.ssh/id_rsa and encode it in base64 format
  ssh-privatekey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFZRUFwRnMxcTBOM3ZFd25ZV1dERUZkZ3JYZytLeTQzQzlTenA2clJ2UWZrR2RaaXFuY2trdDFTCms5eVk4ZmhwUXJxMCtDdkZYVkg0TTNuWkk3c2dtSHh0eHlPeW9TL20xRzFRdmRXT0FVSVUwdzRnSGJHcDVFMzN1VXpNNzEKTm5teUdWN3hzQmxwb280QjhmanJrVHNNTUlKOC9QZjJzektPcDVGdWhCeEV1R1M0SnNsVG5ZQ0xFeVhTS2ErM0RIZmJpcQpoNkI2dFVvblVjTGdFdkxSanVFb01nUDg5Nk94Z3hLSDRyOU9EOFRBUjBrWkRuMWlIcWlqcmFobVZ4N2hmZTI0VFlWMlBkCitoNnpnMitIU1hxYzg0QW5Ucmo4M2VWNlJNN2E5Tjh5dVFFcDR5aE16WXk3Z01zTmRPUVNiNVJCamNZamJLalpwam54akoKd29aOFFCd1FJSW1uN0hUQitLelMwd3ZjV0c3STlNcjhIUWtDaW92LzdLbFl6bDB6bWd4SDNab3RpUTJTaXNZd2d4cmo0cwpjT1UwZHdrVFVtdld4RkR6RXBhQnFxVjAwWjY2UkdHYWxyUXhoM2NrSXBYMDk0UEI0Y0g4eVErcCtRZFR5cFZhRFRHRTF1Cmd4aTlyKzFkZEcxTzlWVCtPaXpGNnZOQXpyUUxPeGZ4U1lkL3RwaERBQUFGa0xqQlNURzR3VWt4QUFBQUIzTnphQzF5YzIKRUFBQUdCQUtSYk5hdERkN3hNSjJGbGd4QlhZSzE0UGlzdU53dlVzNmVxMGIwSDVCbldZcXAzSkpMZFVwUGNtUEg0YVVLNgp0UGdyeFYxUitETjUyU083SUpoOGJjY2pzcUV2NXRSdFVMM1ZqZ0ZDRk5NT0lCMnhxZVJOOTdsTXpPOVRaNXNobGU4YkFaCmFhS09BZkg0NjVFN0REQ0NmUHozOXJNeWpxZVJib1FjUkxoa3VDYkpVNTJBaXhNbDBpbXZ0d3gzMjRxb2VnZXJWS0oxSEMKNEJMeTBZN2hLRElEL1BlanNZTVNoK0svVGcvRXdFZEpHUTU5WWg2b282Mm9abGNlNFgzdHVFMkZkajNmb2VzNE52aDBsNgpuUE9BSjA2NC9OM2xla1RPMnZUZk1ya0JLZU1vVE0yTXU0RExEWFRrRW0rVVFZM0dJMnlvMmFZNThZeWNLR2ZFQWNFQ0NKCnAreDB3ZmlzMHRNTDNGaHV5UFRLL0IwSkFvcUwvK3lwV001ZE01b01SOTJhTFlrTmtvckdNSU1hNCtMSERsTkhjSkUxSnIKMXNSUTh4S1dnYXFsZE5HZXVrUmhtcGEwTVlkM0pDS1Y5UGVEd2VIQi9Na1BxZmtIVThxVldnMHhoTmJvTVl2YS90WFhSdApUdlZVL2pvc3hlcnpRTTYwQ3pzWDhVbUhmN2FZUXdBQUFBTUJBQUVBQUFHQWNYUEFwVnNxTU9IRW9WZklWQ1JzeVBIaXdECjNqbzVnTTk2VlRxSS9rNWV6MktNT2JqSUdZZWhiaHdNNEFJeDdzd3c2NzY0SWt1YXZYdHZGNk82aFF3eEVpUWwvbGtDZHgKZjhrRmdGclVNeWhpQlAxWjBBMzkvWHhGVHNNZEZwbmxmS3NBdXF2cG9XUDZqYk8ySXVOT0l1VXhUN3g1RVRwaG9lMXJVSQp2dHhQdmY1bGFLaU4yQWJZZnd3YmFGRG9URnVsK050TXplUFhNdTZBV1RvSFJPSWRCYzg3aWNWV1VhUmV4V2YwNEtpR3F1CkVERis1TGoyVzI2T1RuOHptcERYK0FIVU9Gemg4ZjZmMkhwb2JaaHpkUHkvRVZGdk9XQTk2Sm9jeEEvZ1BmS1RscUpOOWwKbFpRdjRkdkhEQUdUSnF4UGlaYW9BODNmU3hzTTlrWFBPQWdya2t6T3c3T2dTOG1DdlpRTWxneEFvZkxQYW5ES1VUR3F2NQozUnorSXNoaHdzZDlFWGtZS3NsNDRHRWFqV3I0SWRTbERyTTRMd0lhanlzOVZhRFN0K2RncGhJanRENGRoVDR6N0RmQys0CmEySFR0ZlZ4SEl6c1dmN0lzRUZtTGdqbkdZa3A2dE16VVdkODJnQzNxN2kvTHZ4eWFaeDNnZ0tDUXFjL2t0MFVneEFBQUEKd0VsNno5cW5IMnhpOXRqTWpqaTE1b2E3WGNiSW0wNENSdXRIdDJrcncwZGxaaXRGVzVvT2JKT0tBb2lRTUxSMEY5dDAxTQo4aFFib1lid2FrdnhpWjEyZnMzZGR6Ky9aQ1pxV2RhQ0kybFovN2I1TUFSVm00TDl4cHdZNlU5NDdqaFp5UklZdE82WTdVCkM2UGpubHhabkw4L3NWeWdxUUc2c0RRUFdGdlFxbVpheW1oWlplUktreU1FalJXQVpRSldnd1hPR0c2WWl5d1BjSTdyazUKNE5jcFFiL1pYTXJnczhqeEpZZzlzZXpWWktrcFk5ZzN3b1RuMkgvV2JiZFFnL2RnQUFBTUVBempaY2c3Rm9GV093V2R4awphaGRHZUVOWE9zZFhMNVpYV2NLTk11YjZmV2NpeE1tY1ExcXdVOWtidHhjRktQNG9meUMweFpKNFBicVJBSnlROTNvMktjCnNZcys4dWhlV0lhUjBvdVdNanBlSGltcVo1S1MyRmZxWWZMTU5RTXNKMFA4bzJjQVk2R3hnWmI4Nm02Z3Z5Mk8ra2pINkEKZWVES293QUpBd2p2ZFZqVWJpSUxNbHNvcG1tdU92ZytxT1kvZHFON08yanQxbGplT3FrcTVEZ1d0Z1htWjdnNzViK0NjRwoxZ3o5NEFJUnhub05qeHRORHphTG5kRUlOU3BRa0pBQUFBd1FETUNjdWowbXBOeTFOVHh4UVkxT3FjWmFFS29EOURGWXBmClFnZU1PRkJ4dVZHMndXR1lKcTBQM0dTZ3p0NUV5N0c1SXA5MFgyaWFoT1A1VmYyU05ZdGNnbGRCS2FMVDRPMXBVQ2ZiRlEKZldacERyNnQvMjZLRDN3K0NKdm9vR0FTTEZkTzFBYWN0U2xDVnpIUUVYci9xY3puZ1Azd0pKV1dOL1JOc2wvVVY0RWpubgpjdTRNZXNlVFhUM0RVQTQ0V0dJVFY0R3JlN2RmNGtWRnpibTBxSzVYcjJxY28rdjByOGpCVTZvMklaK05TYnBSanhpdUFmCkozWGE5bmRkL2hKZXNBQUFBWGRXSjFiblIxUUdsd0xURTNNaTB6TVMwek15MHlNeklCQWdNRQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0=

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: golang-service-account
secrets:
  - name: basic-user-pass # Credentials for container registry
  - name: git-user # Credentials for private git repository.

--- 

apiVersion: v1
kind: Secret
metadata:
  name: github-interceptor-secret
type: Opaque
data:
  secretToken: MTIzNDU2Nw== ## secret token from github webhook